### ISSUE TITLE
Not available in Statamic Marketplace

### ISSUE THREAD

**Issue by lelamka** [reachweb/statamic-resrv#57]
@afonic I wanted to use this addon for my project but couldn't find it in marketplace, is there any way to add it there or can I buy it from another place?

**Comment by afonic** [comment]
Hello @lelamka the addon is still on development and we are currently upgrading it for Statamic 4 and creating a general checkout view, because right now it has none.

You can get in touch with me at iosif@reach.gr with some details about your use case and I can help you integrate it with your project if you wish.
